default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

development:
  <<: *default
  database: batgestionale_development

test:
  <<: *default
  database: batgestionale_test

simulation:
  <<: *default
  database: batgestionale_simulation

staging:
  <<: *default
  database: batgestionale_staging

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
